use std::time::Duration;

pub const NFT_BACKUP: &str = "/run/iicpc-lockdown/pre_lockdown.nft";
pub const NFT_LOCKDOWN_SCRIPT: &str = "/run/iicpc-lockdown/lockdown.nft";
pub const NFT_SECOND_WRITE_ONCE_BACKUP: &str = "/run/iicpc-lockdown/system_wo_backup.nft";
pub const CF_URL: &str = "https://codeforces.com";
pub const PROXY_HOST: &str = "127.0.0.1";
pub const PROXY_PORT: u16 = 8080;
pub const BROWSERS: &[&str] = &[
    "/usr/bin/firefox",
    "/usr/bin/chromium-browser",
    "/usr/bin/google-chrome-stable",
    "/usr/bin/google-chrome",
    "/usr/bin/brave",
    "/usr/bin/chromium",
    "/usr/bin/microsoft-edge",
];

use phf::phf_map;

pub const BROWSER_TO_PATH: phf::Map<&'static str, &'static str> = phf_map! {
    "chrome" => "/usr/bin/google-chrome",
    "google-chrome" => "/usr/bin/google-chrome",
    "chromium" => "/usr/bin/chromium",
    "brave" => "/usr/bin/brave-browser",
    "brave-browser" => "/usr/bin/brave-browser",
    "edge" => "/usr/bin/microsoft-edge",
    "microsoft-edge" => "/usr/bin/microsoft-edge",
    "firefox" => "/usr/bin/firefox",
};
pub const BROWSER_TARGETS_BASE_NAMES: &[&str] = &[
    "firefox",
    "chromium",
    "chrome",
    "brave",
    "msedge",
    "edge",
    "google-chrome",
    "microsoft-edge",
    "chromium-browser",
    "google-chrome-stable",
    "brave-browser",
];
pub const LOG_DIR: &str = "/var/log/iicpc-lockdown/";
pub const RUNTIME_DIR: &str = "/run/iicpc-lockdown/";
pub const LOCK_FILE: &str = "/run/iicpc-lockdown/init.lock";
pub const TEST_MODE: bool = false;
pub const BLOCK_CODE_EDITORS: bool = true;
pub const BLOCK_INTERPRETERS_AND_COMPILERS: bool = true;
pub const BLACKLIST: &[&str] = &[
    // [SECTION: LOCAL LLMS & AI RUNTIMES]
    "ollama",
    "lm-studio",
    "gpt4all",
    "llama",
    "koboldcpp",
    "koboldai",
    "oobabooga",
    "text-generation",
    "localai",
    "jan-app",
    "llama",
    "gpt4all",
    "lmstudio",
    "textgen",
    "rwkv",
    "mistral",
    "huggingface",
    "langchain",
    "privategpt",
    "copilot",
    "whisper",
    // [SECTION: REMOTE DESKTOP & SCREEN SHARING]
    "teamviewer",
    "anydesk",
    "rustdesk",
    "chrome-remote",
    "remotedesktop",
    "mstsc",
    "vnc",
    "nomachine",
    "logmein",
    "parsec",
    "sunshine",
    "moonlight",
    "splashtop",
    "screenconnect",
    "ammyy",
    "supremo",
    // [SECTION: COMMUNICATION & COLLABORATION]
    "discord",
    "slack",
    "skype",
    "telegram",
    "whatsapp",
    "signal",
    "viber",
    "teams",
    "zoom",
    "webex",
    "gotomeeting",
    "element",
    "mattermost",
    // [SECTION: WEB BROWSERS]
    "chrome",
    "firefox",
    "brave",
    "opera",
    "edge",
    "msedge",
    "chromium",
    "vivaldi",
    "tor",
    "tor-browser",
    "librewolf",
    "waterfox",
    "safari",
    "yandex",
    "epiphany",
    "konqueror",
    // [SECTION: VIRTUALIZATION & SANDBOXING]
    "qemu",
    "virtualbox",
    "vbox",
    "vmware",
    "vmwp",
    "xen",
    "dosbox",
    "sandboxie",
    "wsl",
    "docker",
    "podman",
    "bluestacks",
    "nox",
    "ldplayer",
    // [SECTION: NETWORK TUNNELING & PROXIES]
    "ngrok",
    "cloudflared",
    "localtunnel",
    "frp",
    "chisel",
    "proxifier",
    "charles",
    "fiddler",
    "wireshark",
    "nmap",
    // [SECTION: CHEAT ENGINES & PROCESS HACKERS]
    "cheatengine",
    "processhacker",
    "procexp",
    "ida",
    "ghidra",
    "x64dbg",
    "ollydbg",
    // [SECTION: TERMINALS & SHELLS]
    // "bash",
    // "sh",
    // "zsh",
    "fish",
    "dash",
    "ksh",
    "tcsh",
    "csh",
    // Surrogates / shell runners
    "busybox",
    "env",
    "setsid",
    "script",
    "expect",
    "tmux",
    "screen",
    "byobu",
    // Common terminal emulators
    "gnome-terminal",
    "gnome-terminal-server",
    "konsole",
    "xfce4-terminal",
    "mate-terminal",
    "lxterminal",
    "qterminal",
    "tilix",
    "terminator",
    "alacritty",
    // "kitty",
    "wezterm",
    "hyper",
    "tabby",
    "rio",
    "cool-retro-term",
    "guake",
    "yakuake",
    "tilda",
    "eterm",
    "xterm",
    "rxvt",
    "urxvt",
    "aterm",
    "st",
    "sakura",
    "foot",
    "iterm",
    "mintty",
    // Multiplexers & remote shells
    "ssh",
    "scp",
    "sftp",
    "mosh",
    "",
];
pub const CODE_EDITORS: &[&str] = &[
    "code",
    "code-oss",
    "vscode",
    "sublime_text",
    "atom",
    "notepadqq",
    "gedit",
    "kate",
    "vim",
    "nvim",
    "emacs",
];

pub const INTERPRETERS_AND_COMPILERS: &[&str] = &[
    "gcc",
    "g++",
    "clang",
    "clang++",
    "javac",
    "java",
    // TODO: [COMMENTED FOR TESTING PHASE] UNCOMMENT DURING RELEASE
    // "rustc",
    // "cargo",
    "go",
    "python",
    "python3",
    "node",
    "ipython",
    "jupyter",
    "anaconda",
    "miniconda",
    "npm",
    "pip",
    "make",
    "cmake",
    "ninja",
    "scons",
    "meson",
    "gdb",
    "lldb",
    "rr",
    "rlwrap",
    "screen",
    "tmux",
];
pub const SCAN_INTERVAL: Duration = Duration::from_secs(10);
pub const PROC_BASELINE_FILE: &str = "/run/iicpc-lockdown/procb.json";
pub const SYSTEM_CRITICAL: &[&str] = &[
    "systemd", "dbus", "kwin", "plasma", "Xwayland", "Xorg", "sddm", "gdm", "lightdm", "ssh",
    "login", "init",
];
pub const SAFE_CHILD_TYPES: &[&str] = &["bash", "sh", "zsh", "fish", "kitten"];
pub const STATE_FILE: &str = "/tmp/lockdown_audio_state";
